name: Set required environment variables
description: Set required environment variables
runs:
  using: composite
  steps:
    - name: Set variables
      shell: bash
      run: |
        gh_repo=${{ github.repository }}
        github_event=$(cat <<EVENT
        ${{ toJson(github.event) }}
        EVENT
        )
        publish_image=$(jq -r 'if has("release") and ((.release.draft?  or .release.prelease?) | not) then "true" else "" end' <<< $github_event)

        { 
          echo "GH_REPO=${gh_repo,,}"
          echo "PUBLISH_IMAGE=${publish_image}"
        } | tee -a $GITHUB_ENV